version: '3.4'

services:
  app:
    image: flask-boilerplate
    build:
      context: .
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_CONFIG=app.config.DevelopmentConfig
    volumes:
      - .:/usr/src/app
    ports:
     - "80:5000"
    entrypoint: ["./entrypoint.sh"]
    command: ["flask", "run", "--host", "0.0.0.0"]
    
